config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sites
  resources :groups
  resources :categories
  resources :rules do
    collection { post :sort }
  end

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :site
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :rule
  has_many :sites, through: :categorizations
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :rules
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :group
  belongs_to :category
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :categorizations
  has_many :categories, through: :categorizations
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, through: :memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
    
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)

    if @category.save
      
      flash[:success] = "Categoria cadastrada com sucesso!"
      redirect_to @category
    else
      render 'new'
    end
  end
  
  def edit 
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Categoria Atualizada!"
      redirect_to @category
    else
      render 'edit'
    end
  end
  
  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Categoria deletada!"
    redirect_to categories_url
  end
  
  private
  
  def category_params
    params.require(:category).permit(:name)
  end
  
  


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end
  
  def show
    @group = Group.find(params[:id])
    
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group	=	Group.new(group_params)

    if @group.save
      
      flash[:success] = "Grupo cadastrado com sucesso!"
      redirect_to @group
    else
      render 'new'
    end
  end
  
  def edit 
    @group = Group.find(params[:id])
  end
  
  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "Grupo atualizado!"
      redirect_to @group
    else
      render 'edit'
    end
  end
  
  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Grupo deletado!"
    redirect_to groups_url
  end
  
  private
  
  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  
  def index

    @rules = Rule.order("position")
    #@groups = Group.all
  end
  
  def show
    @rule = Rule.find(params[:id])
    
  end
  
  def new
    @rule = Rule.new
  end
  
  def create
    @rule = Rule.new(rule_params)

    if @rule.save
      
      flash[:success] = "Regra cadastrado com sucesso!"
      redirect_to @rule
    else
      render 'new'
    end
  end
  
  def edit 
    @rule = Rule.find(params[:id])
  end
  
  def update
    @rule = Rule.find(params[:id])
    if @rule.update_attributes(rule_params)
      flash[:success] = "Perfil atualizado!"
      redirect_to @rule
    else
      render 'edit'
    end
  end
  
  def destroy
    Rule.find(params[:id]).destroy
    flash[:success] = "Usuário deletado!"
    redirect_to rules_url
  end
  
  def sort
    params[:rule].each_with_index do |id, index|
      Rule.update(id, position: index+1)
    end
  render nothing: true
 end

  private
  
  def rule_params
    params.require(:rule).permit(:name, :action, :order, :option, :group_id, :category_id, :position)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.all
    @categories = Category.all
  end
  
  def show
    @site = Site.find(params[:id])
    
  end
  
  def new
    @site = Site.new
  end
  
  def create
    @site = Site.new(site_params)

    if @site.save
      
      flash[:success] = "Usuário cadastrado com sucesso!"
      redirect_to @site
    else
      render 'new'
    end
  end
  
  def edit 
    @site = Site.find(params[:id])
  end
  
  def update
    @site = Site.find(params[:id])
    if @site.update_attributes(site_params)
      flash[:success] = "Perfil atualizado!"
      redirect_to @site
    else
      render 'edit'
    end
  end
  
  def destroy
    Site.find(params[:id]).destroy
    flash[:success] = "Usuário deletado!"
    redirect_to sites_url
  end
  
  private
  
  def site_params
    params.require(:site).permit(:name, :category_ids)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user	=	User.new(user_params)

    if @user.save
      
      flash[:success] = "Usuário cadastrado com sucesso!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Perfil atualizado!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Usuário deletado!"
    redirect_to users_url
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :proxy_pass, :password, :group_ids)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<li>
  <%= link_to category.name, category %>  
  
  <%# if current_user.admin? && !current_user?(user) %>
    <%= link_to "Apagar", category,  method: :delete, data: { confirm: "Tem certeza?" } %>
  <%# end %>
</li>

app/views/categories/edit.html.erb
<h1>Criar categoria</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	form_for(@category) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome"	%>
	  <%= f.text_field	:name	%>
	  <%= f.submit	"Criar Categoria", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<h1>Categorias</h1>

<ul class="categories">
  <% @categories.each do |category| %>
  
    <%# link_to category.name, category %>
    <!-- carrega partial como acima -->
    <%= render category %>
    
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>Criar Categoria</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	form_for(@category) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome"	%>
	  <%= f.text_field	:name	%>
	  <%= f.submit	"Criar Categoria", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<h1>Usuário</h1>

<%= @category.name %>

<h2><%=link_to(h(@category.name), user_path(@category)) %></h2>

app/views/groups/_group.html.erb
<li>
  <%= link_to group.name, group %>  
  
  <%# if current_user.admin? && !current_user?(user) %>
    <%= link_to "Apagar", group,  method: :delete, data: { confirm: "Tem certeza?" } %>
  <%# end %>
</li>

app/views/groups/index.html.erb
<h1>Grupos</h1>

<ul class="groups">
  <% @groups.each do |group| %>
  
    <%# link_to group.name, group %>
    <!-- carrega partial como acima -->
    <%= render group %>
    
  <% end %>
</ul>

app/views/groups/new.html.erb
<h1>Criar Grupo</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@group) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome" %>
          <%= f.text_field :name %>
          <%= f.submit "Criar Grupo", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<h1>Grupos</h1>

<%= @group.name %>

<h2><%=link_to(h(@group.name), group_path(@group)) %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Piroxy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rules/index.html.erb
<h1>Regras</h1>
  
<table id="rules" >

  <thead>	
    <tr>
      <th>Ação</th>
      <th>Grupo</th>
      <th>Opção</th>
      <th>Categoria</th>
    </tr>
  </thead>
  
  <tbody data-update-url="<%= sort_rules_url %>">
  <% @rules.each do |rule| %>
    
    	<%= content_tag_for :tr, rule do %>	

        <td><%= rule.action %> </td>
        <td><%= rule.group.name %></td>    
          <%#= link_to "Apagar", rule,  method: :delete, data: { confirm: "Tem certeza?" } %>
        <td><%= rule.option %></td>
        <td><%= rule.category.name %></td>
      <% end %>
  <% end %>
    </tbody>

</table>

app/views/rules/new.html.erb
<h1>Criar Regra</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@rule) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :Ação %>
      <%= f.select :action, ['allow', 'deny']%>
      <%#= f.label :group_id, "Departamento" %>
      <%= f.collection_select(:group_id, Group.all, :id, :name, :include_blank => true) %>
      <%#= f.select :group_ids, Group.all.collect {|x| [x.name, x.id]}, {} %>
      <!-- Esse debaixo funciona do mesmo jeito do de cima -->
      <%#= collection_select(:group, :group_id, Group.all, :id, :name) %>
      <%#= f.label :Opcao %>
      <%= f.select :option, ['url_regex', 'dstdomain']%>
      <%#= f.label :category_id, "Departamento" %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, :include_blank => true) %>

      <%= f.submit  "Criar Regra", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rules/show.html.erb
<h1>Rules</h1>
<%= @rule.action %>

<%= @rule.group.name %>
  

app/views/sites/_site.html.erb
<li>
  <%= site.name, site.category %>  
  
  <%# if current_user.admin? && !current_user?(user) %>
    <%= link_to "Apagar", site,  method: :delete, data: { confirm: "Tem certeza?" } %>
  <%# end %>
</li>

app/views/sites/index.html.erb
<h1>Sites</h1>



aaaaaaaaaaaa
 <% @sites.each do |site| %>
   <ul>
     <li>
       <%= site.name %>
         <% site.categories.each do |category| %>
            <li>
              <%= category.name %>
            </li>
         <% end %>
     </li>
   </ul>
 <% end %>    

app/views/sites/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@site) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome" %>
          <%= f.text_field      :name   %>
          <%#= f.select :categories, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
          <%= f.collection_select :category_ids, Category.all, :id, :name %>

          <%= f.submit  "Criar Site",        class:  "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/sites/show.html.erb
<h1>Sites</h1>

<%= @site.name %>

<h2><%=link_to(h(@site.name), site_path(@site)) %></h2>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>  
  
  <%# if current_user.admin? && !current_user?(user) %>
    <%= link_to "Apagar", user,  method: :delete, data: { confirm: "Tem certeza?" } %>
  <%# end %>
</li>

app/views/users/edit.html.erb
<h1>Editar Site</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	form_for(@user) do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome"	%>
	  <%= f.text_field :name %>
	  <%= f.submit	"Criar Site",	class:	"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Usuários</h1>

<ul class="users">
  <% @users.each do |user| %>
  
    <%# link_to user.name, user %>
    <!-- carrega partial como acima -->
    <%= render user %>
    
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Criar Usuário</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%=	form_for(@user)	do |f| %>
      <%# render 'shared/error_messages', object: f.object %>
      <%= f.label :name, "Nome"	%>
	  <%= f.text_field	:name	%>
	  <%= f.label	:email	%>
	  <%= f.email_field	:email %>
	  <%= f.label	:proxy_pass, "Senha Proxy" %>
	  <%= f.password_field	:proxy_pass	%>
	  <%= f.label :group, "Grupo"	%>
	  <%#= f.select :groups, Group.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
	  <%= f.collection_select :group_ids, Group.all, :id, :name, {:multiple => true} %>

	  <%#= f.select :group_ids, Group.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
	  
	  <%= f.submit	"Criar Usuário",	class:	"btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Usuário</h1>

<%=	@user.name	%>,	<%=	@user.email	%>

<h2><%=link_to(h(@user.name), user_path(@user)) %></h2>
<p><%= @user.email %></p>